name: Atualiza toda a infra do homelab

on:
  push:
    branches:
      - main

jobs: 
  apply:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci

      - name: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
        
